# Generated by Django 3.2.9 on 2021-11-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=50, verbose_name='Имя Фамилия')),
                ('slug', models.SlugField(unique=True)),
                ('tutor_phone', models.IntegerField(max_length=13, verbose_name='телефон')),
                ('tutor_info', models.TextField(verbose_name='инфо')),
            ],
        ),
    ]
